# Generated by Django 5.2 on 2025-05-28 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='full_name',
        ),
    ]
